# Generated by Django 5.0.6 on 2025-12-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_add_arch_task_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('architect', 'Architect'), ('senior_architect', 'Senior Architect'), ('junior_architect', 'Junior Architect'), ('managing_director', 'Managing Director'), ('site_engineer', 'Site Engineer'), ('senior_civil_engineer', 'Senior Civil Engineer'), ('junior_civil_engineer', 'Junior Civil Engineer'), ('finance', 'Finance'), ('accountant', 'Accountant'), ('project_manager', 'Project Manager'), ('designer', 'Designer'), ('senior_interior_designer', 'Senior Interior Designer'), ('junior_interior_designer', 'Junior Interior Designer'), ('draughtsman', 'Draughtsman'), ('visualiser_3d', '3D Visualiser'), ('qs', 'QS / Estimator'), ('procurement', 'Procurement'), ('client_liaison', 'Client Liaison'), ('intern', 'Intern / Trainee'), ('viewer', 'Viewer (read-only)')], default='architect', max_length=32),
        ),
    ]
