# Generated by Django 5.0.6 on 2025-12-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_tasktemplate_id_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('architect', 'Architect'), ('senior_architect', 'Senior Architect'), ('junior_architect', 'Junior Architect'), ('managing_director', 'Managing Director'), ('site_engineer', 'Site Engineer'), ('senior_civil_engineer', 'Senior Civil Engineer'), ('junior_civil_engineer', 'Junior Civil Engineer'), ('finance', 'Finance'), ('accountant', 'Accountant'), ('project_manager', 'Project Manager'), ('designer', 'Designer'), ('senior_interior_designer', 'Senior Interior Designer'), ('junior_interior_designer', 'Junior Interior Designer'), ('draughtsman', 'Draughtsman'), ('visualiser_3d', '3D Visualiser'), ('qs', 'QS / Estimator'), ('procurement', 'Procurement'), ('client_liaison', 'Client Liaison'), ('intern', 'Intern / Trainee'), ('viewer', 'Viewer (read-only)')], max_length=32, unique=True)),
                ('clients', models.BooleanField(default=False)),
                ('leads', models.BooleanField(default=False)),
                ('projects', models.BooleanField(default=False)),
                ('site_visits', models.BooleanField(default=False)),
                ('finance', models.BooleanField(default=False)),
                ('invoices', models.BooleanField(default=False)),
                ('docs', models.BooleanField(default=False)),
                ('team', models.BooleanField(default=False)),
                ('users', models.BooleanField(default=False)),
                ('settings', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
