# Generated by Django 5.0.6 on 2025-12-12 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_alter_invoice_invoice_number_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts_generated', to=settings.AUTH_USER_MODEL),
        ),
    ]
