# Generated by Django 5.0.6 on 2025-12-14 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_payment_cashbook_entries(apps, schema_editor):
    Payment = apps.get_model('portal', 'Payment')
    Transaction = apps.get_model('portal', 'Transaction')

    existing_payment_ids = set(
        Transaction.objects.exclude(payment_id=None).values_list('payment_id', flat=True)
    )

    new_entries = []
    for payment in Payment.objects.select_related(
        'invoice',
        'invoice__project',
        'invoice__project__client',
        'invoice__lead',
        'invoice__lead__client',
    ):
        if payment.pk in existing_payment_ids:
            continue
        invoice = payment.invoice
        project = getattr(invoice, 'project', None)
        project_id = getattr(invoice, 'project_id', None)

        client_id = None
        if project_id:
            client_id = getattr(project, 'client_id', None)
        else:
            lead = getattr(invoice, 'lead', None)
            client_id = getattr(lead, 'client_id', None) if lead else None

        invoice_number = (getattr(invoice, 'invoice_number', None) or '').strip() or str(invoice.pk)
        description = f"Payment received · Invoice {invoice_number}"
        if project and getattr(project, 'code', None):
            description = f"Payment received · {project.code} · Invoice {invoice_number}"

        remarks_parts = []
        if getattr(payment, 'method', None):
            remarks_parts.append(f"Method: {payment.method}")
        if getattr(payment, 'reference', None):
            remarks_parts.append(f"Ref: {payment.reference}")
        remarks = " | ".join(remarks_parts)

        new_entries.append(
            Transaction(
                date=payment.payment_date,
                description=description[:255],
                debit=0,
                credit=payment.amount,
                payment_id=payment.pk,
                related_project_id=project_id,
                related_client_id=client_id,
                related_person_id=getattr(payment, 'received_by_id', None),
                recorded_by_id=getattr(payment, 'recorded_by_id', None),
                remarks=remarks,
            )
        )

    if new_entries:
        Transaction.objects.bulk_create(new_entries)


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_alter_receipt_generated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment',
            field=models.OneToOneField(blank=True, help_text='Auto-linked payment income entry (system generated).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashbook_entry', to='portal.payment'),
        ),
        migrations.CreateModel(
            name='StaffActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('projects', 'Projects'), ('tasks', 'Tasks'), ('site_visits', 'Site Visits'), ('finance', 'Finance'), ('docs', 'Docs'), ('team', 'Team'), ('users', 'Users'), ('settings', 'Settings'), ('system', 'System')], default='system', max_length=50)),
                ('message', models.CharField(max_length=500)),
                ('related_url', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(backfill_payment_cashbook_entries, migrations.RunPython.noop),
    ]
