# Generated by Django 5.0.6 on 2025-12-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_transaction_payment_staffactivity'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project', 'created_at'], name='portal_docu_project_f1cfb2_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_type'], name='portal_docu_file_ty_84307f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='portal_invo_status_cd42a3_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='portal_invo_invoice_2885d2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='portal_noti_user_id_338b73_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='portal_paym_payment_dec975_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'payment_date'], name='portal_paym_invoice_d335d5_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['current_stage'], name='portal_proj_current_ece6b2_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['health_status'], name='portal_proj_health__ab7c32_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_type'], name='portal_proj_project_17e957_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['start_date'], name='portal_proj_start_d_4159b6_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['expected_handover'], name='portal_proj_expecte_6b6244_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['updated_at'], name='portal_proj_updated_8b703f_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_date'], name='portal_rece_receipt_ce0d89_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['invoice', 'receipt_date'], name='portal_rece_invoice_a30165_idx'),
        ),
        migrations.AddIndex(
            model_name='siteissue',
            index=models.Index(fields=['project', 'status'], name='portal_site_project_02b86d_idx'),
        ),
        migrations.AddIndex(
            model_name='siteissue',
            index=models.Index(fields=['status', 'raised_on'], name='portal_site_status_06c0e7_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisit',
            index=models.Index(fields=['project', 'visit_date'], name='portal_site_project_288b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisit',
            index=models.Index(fields=['visited_by', 'visit_date'], name='portal_site_visited_cce360_idx'),
        ),
        migrations.AddIndex(
            model_name='staffactivity',
            index=models.Index(fields=['created_at'], name='portal_staf_created_6a7044_idx'),
        ),
        migrations.AddIndex(
            model_name='staffactivity',
            index=models.Index(fields=['actor', 'created_at'], name='portal_staf_actor_i_be292a_idx'),
        ),
        migrations.AddIndex(
            model_name='staffactivity',
            index=models.Index(fields=['category', 'created_at'], name='portal_staf_categor_c3f106_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status', 'due_date'], name='portal_task_assigne_364f95_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status', 'due_date'], name='portal_task_project_fa37de_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='portal_tran_date_14622c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['related_project', 'date'], name='portal_tran_related_c12aa1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['related_client', 'date'], name='portal_tran_related_cfebe5_idx'),
        ),
    ]
