# Generated by Django 5.0.6 on 2025-12-15 04:12

from django.db import migrations, models


def set_payment_transaction_category(apps, schema_editor):
    Transaction = apps.get_model('portal', 'Transaction')
    Transaction.objects.filter(payment__isnull=False, category='').update(category='client_payment')


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_document_portal_docu_project_f1cfb2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('client_payment', 'Client payment'), ('salary', 'Salary'), ('misc', 'Misc expense'), ('project_expense', 'Project expense'), ('other_income', 'Other income'), ('other_expense', 'Other expense')], db_index=True, default='', max_length=32),
        ),
        migrations.RunPython(set_payment_transaction_category, migrations.RunPython.noop),
        migrations.AddField(
            model_name='user',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Optional: used for payroll tracking (monthly amount).', max_digits=12),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', 'date'], name='portal_tran_categor_aca6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['related_person', 'date'], name='portal_tran_related_85a90d_idx'),
        ),
    ]
