# Generated by Django 5.0.6 on 2025-12-15 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def bootstrap_accounts(apps, schema_editor):
    Account = apps.get_model('portal', 'Account')
    Transaction = apps.get_model('portal', 'Transaction')
    cash, _ = Account.objects.get_or_create(
        name='Cash',
        defaults={'account_type': 'cash', 'opening_balance': 0, 'is_active': True},
    )
    Transaction.objects.filter(account__isnull=True).update(account=cash)


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_transaction_category_user_monthly_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('client_payment', 'Client payment'), ('client_advance', 'Client advance'), ('vendor_payment', 'Vendor payment'), ('salary', 'Salary'), ('reimbursement', 'Reimbursement'), ('transfer', 'Transfer'), ('misc', 'Misc expense'), ('project_expense', 'Project expense'), ('other_income', 'Other income'), ('other_expense', 'Other expense')], db_index=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('upi', 'UPI'), ('other', 'Other')], default='cash', max_length=16)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['account_type', 'name'], name='portal_acco_account_c3dd05_idx'), models.Index(fields=['is_active', 'name'], name='portal_acco_is_acti_37802e_idx')],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='portal.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='portal.account'),
        ),
        migrations.RunPython(bootstrap_accounts, migrations.RunPython.noop),
        migrations.CreateModel(
            name='BankStatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='bank_statements/')),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_imports', to='portal.account')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statement_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive = credit (money in). Negative = debit (money out).', max_digits=12)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('matched_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_statement_lines', to='portal.transaction')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='portal.bankstatementimport')),
            ],
            options={
                'ordering': ['-line_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_number', models.CharField(blank=True, max_length=100)),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='unpaid', max_length=16)),
                ('category', models.CharField(choices=[('project_expense', 'Project expense'), ('misc', 'Misc expense'), ('other_expense', 'Other expense')], default='project_expense', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='bills/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='portal.project')),
            ],
            options={
                'ordering': ['-bill_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(blank=True, max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_payments', to='portal.account')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='portal.bill')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='bill_payment',
            field=models.ForeignKey(blank=True, help_text='Auto-linked vendor payment entry (system generated).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashbook_entries', to='portal.billpayment'),
        ),
        migrations.CreateModel(
            name='ClientAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(blank=True, max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_advances', to='portal.account')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances', to='portal.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances', to='portal.project')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances_received', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='client_advance',
            field=models.ForeignKey(blank=True, help_text='Auto-linked client advance entry (system generated).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashbook_entries', to='portal.clientadvance'),
        ),
        migrations.CreateModel(
            name='ClientAdvanceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='portal.clientadvance')),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_allocations', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_allocations', to='portal.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='submitted', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_claims_approved', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_claims', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_claims', to='portal.project')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseClaimAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='expense_claims/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='portal.expenseclaim')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseClaimPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(blank=True, max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_claim_payments', to='portal.account')),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='portal.expenseclaim')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_claim_payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='expense_claim_payment',
            field=models.ForeignKey(blank=True, help_text='Auto-linked reimbursement entry (system generated).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashbook_entries', to='portal.expenseclaimpayment'),
        ),
        migrations.CreateModel(
            name='ProjectFinancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planned_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('planned_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_plan', to='portal.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], default='planned', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='portal.invoice')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='portal.project')),
            ],
            options={
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringTransactionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('direction', models.CharField(choices=[('debit', 'Debit (expense)'), ('credit', 'Credit (income)')], default='debit', max_length=16)),
                ('category', models.CharField(choices=[('client_payment', 'Client payment'), ('client_advance', 'Client advance'), ('vendor_payment', 'Vendor payment'), ('salary', 'Salary'), ('reimbursement', 'Reimbursement'), ('transfer', 'Transfer'), ('misc', 'Misc expense'), ('project_expense', 'Project expense'), ('other_income', 'Other income'), ('other_expense', 'Other expense')], default='misc', max_length=32)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('day_of_month', models.PositiveSmallIntegerField(default=1)),
                ('next_run_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_rules', to='portal.account')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_rules', to='portal.project')),
            ],
            options={
                'ordering': ['next_run_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurring_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='portal.recurringtransactionrule'),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='portal_vend_name_6b410c_idx')],
            },
        ),
        migrations.AddField(
            model_name='recurringtransactionrule',
            name='related_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_rules', to='portal.vendor'),
        ),
        migrations.AddField(
            model_name='bill',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='portal.vendor'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='portal.vendor'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'date'], name='portal_tran_account_939d73_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['related_vendor', 'date'], name='portal_tran_related_a6e017_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementimport',
            index=models.Index(fields=['account', 'created_at'], name='portal_bank_account_bd58a9_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['statement', 'line_date'], name='portal_bank_stateme_7dd8e3_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['line_date'], name='portal_bank_line_da_4c18dd_idx'),
        ),
        migrations.AddIndex(
            model_name='billpayment',
            index=models.Index(fields=['payment_date'], name='portal_bill_payment_47ca4a_idx'),
        ),
        migrations.AddIndex(
            model_name='billpayment',
            index=models.Index(fields=['bill', 'payment_date'], name='portal_bill_bill_id_c2364b_idx'),
        ),
        migrations.AddIndex(
            model_name='clientadvance',
            index=models.Index(fields=['received_date'], name='portal_clie_receive_8e17eb_idx'),
        ),
        migrations.AddIndex(
            model_name='clientadvance',
            index=models.Index(fields=['client', 'received_date'], name='portal_clie_client__10b711_idx'),
        ),
        migrations.AddIndex(
            model_name='clientadvance',
            index=models.Index(fields=['project', 'received_date'], name='portal_clie_project_e89b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='clientadvanceallocation',
            index=models.Index(fields=['invoice', 'created_at'], name='portal_clie_invoice_bfb23a_idx'),
        ),
        migrations.AddIndex(
            model_name='clientadvanceallocation',
            index=models.Index(fields=['advance', 'created_at'], name='portal_clie_advance_df9634_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseclaim',
            index=models.Index(fields=['status', 'expense_date'], name='portal_expe_status_86f1b5_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseclaim',
            index=models.Index(fields=['employee', 'expense_date'], name='portal_expe_employe_a0303e_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseclaimpayment',
            index=models.Index(fields=['payment_date'], name='portal_expe_payment_5bf22c_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmilestone',
            index=models.Index(fields=['project', 'status'], name='portal_proj_project_b341c9_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmilestone',
            index=models.Index(fields=['due_date'], name='portal_proj_due_dat_885bac_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransactionrule',
            index=models.Index(fields=['is_active', 'next_run_date'], name='portal_recu_is_acti_31a6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['status', 'due_date'], name='portal_bill_status_d28a13_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['bill_date'], name='portal_bill_bill_da_1a22db_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['vendor', 'bill_date'], name='portal_bill_vendor__9998c5_idx'),
        ),
    ]
