# Generated by Django 5.0.6 on 2025-12-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_transaction_subcategory_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmprofile',
            name='invoice_sequence_after',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Optional: next invoice will use the number after this value (e.g. 584 → 585).',
                null=True,
            ),
        ),
    ]

