# Generated by Django 5.0.6 on 2026-03-26 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_manage_director_finance_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(default='Novart', max_length=120)),
                ('brand_suffix', models.CharField(default='Architects', max_length=120)),
                ('hero_heading', models.CharField(max_length=255)),
                ('hero_supporting_text', models.TextField()),
                ('hero_cta_phone_label', models.CharField(default='Call Us', max_length=80)),
                ('hero_cta_whatsapp_label', models.CharField(default='WhatsApp Us', max_length=80)),
                ('phone_display', models.CharField(blank=True, max_length=50)),
                ('whatsapp_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('services_heading', models.CharField(default='Services', max_length=120)),
                ('services_intro', models.TextField(blank=True)),
                ('process_heading', models.CharField(default='Process', max_length=120)),
                ('process_intro', models.TextField(blank=True)),
                ('work_heading', models.CharField(default='Selected Work', max_length=120)),
                ('work_intro', models.TextField(blank=True)),
                ('studio_heading', models.CharField(default='Studio', max_length=120)),
                ('studio_body', models.TextField(blank=True)),
                ('contact_heading', models.CharField(default='Contact', max_length=120)),
                ('contact_intro', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='public_site/')),
                ('hero_image_alt', models.CharField(blank=True, max_length=255)),
                ('hero_art_key', models.CharField(choices=[('courtyard-house', 'Courtyard House'), ('atelier-interior', 'Atelier Interior'), ('horizon-masterplan', 'Horizon Masterplan')], default='courtyard-house', max_length=64)),
                ('studio_image', models.ImageField(blank=True, null=True, upload_to='public_site/')),
                ('studio_image_alt', models.CharField(blank=True, max_length=255)),
                ('studio_art_key', models.CharField(choices=[('courtyard-house', 'Courtyard House'), ('atelier-interior', 'Atelier Interior'), ('horizon-masterplan', 'Horizon Masterplan')], default='atelier-interior', max_length=64)),
                ('meta_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('singleton', models.BooleanField(default=True, unique=True)),
            ],
            options={
                'verbose_name': 'Public Site Settings',
            },
        ),
        migrations.CreateModel(
            name='PublicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='portal.publicsitesettings')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PublicProjectHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('project_type', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='public_site/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('art_key', models.CharField(choices=[('courtyard-house', 'Courtyard House'), ('atelier-interior', 'Atelier Interior'), ('horizon-masterplan', 'Horizon Masterplan')], default='courtyard-house', max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_highlights', to='portal.publicsitesettings')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PublicProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_label', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='portal.publicsitesettings')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
