name: studioflow
region: blr

services:
  - name: web
    environment_slug: python
    instance_size_slug: basic-xxs
    instance_count: 1
    http_port: 8080
    git:
      repo_clone_url: https://github.com/itzpraveen/novart.git
      branch: main
    source_dir: .
    build_command: >-
      apt-get update && \
      apt-get install -y libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf-2.0-0 libffi-dev shared-mime-info libharfbuzz0b libfribidi0 && \
      pip install -r requirements.txt && \
      python manage.py collectstatic --noinput
    run_command: gunicorn studioflow.wsgi:application --bind 0.0.0.0:${PORT:-8080}
    routes:
      - path: /
    envs:
      - key: DJANGO_SECRET_KEY
        type: SECRET
        value: change-me
        scope: RUN_TIME
      - key: DJANGO_ALLOWED_HOSTS
        value: ${APP_DOMAIN},*.ondigitalocean.app
        scope: RUN_TIME
      - key: DJANGO_DEBUG
        value: "0"
        scope: RUN_TIME
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://${APP_DOMAIN},https://*.ondigitalocean.app
        scope: RUN_TIME
      - key: DATABASE_URL
        type: SECRET
        value: postgresql://replace-with-connection-string
        scope: RUN_TIME

jobs:
  - name: migrate
    kind: PRE_DEPLOY
    environment_slug: python
    git:
      repo_clone_url: https://github.com/itzpraveen/novart.git
      branch: main
    source_dir: .
    run_command: python manage.py migrate --noinput
    envs:
      - key: DJANGO_SECRET_KEY
        type: SECRET
        value: change-me
      - key: DJANGO_ALLOWED_HOSTS
        value: ${APP_DOMAIN}
      - key: DJANGO_DEBUG
        value: "0"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://${APP_DOMAIN}
      - key: DATABASE_URL
        type: SECRET
        value: postgresql://replace-with-connection-string
