name: studioflow
region: blr

services:
  - name: web
    environment_slug: python
    instance_size_slug: basic-xxs
    instance_count: 1
    http_port: 8080
    git:
      repo_clone_url: https://github.com/itzpraveen/novart.git
      branch: main
    source_dir: .
    build_command: python manage.py collectstatic --noinput
    run_command: gunicorn studioflow.wsgi:application --bind 0.0.0.0:${PORT:-8080}
    routes:
      - path: /
    envs:
      - key: DJANGO_SECRET_KEY
        type: SECRET
        value: EV[1:lgeIZg+A2H+qUG8+O79Oq4+5BLhaZDEm:ENgcR4e9jP5j8V08VLhOvK2m8epVcqfHzA==]
        scope: RUN_TIME
      - key: DJANGO_ALLOWED_HOSTS
        value: ${APP_DOMAIN},*.ondigitalocean.app
        scope: RUN_TIME
      - key: DJANGO_DEBUG
        value: "0"
        scope: RUN_TIME
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://${APP_DOMAIN},https://*.ondigitalocean.app
        scope: RUN_TIME
      - key: DATABASE_URL
        type: SECRET
        value: EV[1:LwiDFhrMM2zax08uzpdzaAhZMPDnKiaY:dFh5Www3K7/jhAyL8iP2ow7hkq/DNH5ZbC2HdYaqKPj23HI0+XShW1ItfzKpqJ6Je84QmQpuJOZP05sdzFhX+nDvwK7fuq6aOafWfU00J0JRtzY+Cs+qBIw3HQXxpbVNEwkIO7mB0UYOAxjTM6oBpN2kd7lmBRkLP6/v+FvCe2Jq6Ktx6tmnH2C+T7WnX898vgsQnX4a]
        scope: RUN_TIME

jobs:
  - name: migrate
    kind: PRE_DEPLOY
    environment_slug: python
    git:
      repo_clone_url: https://github.com/itzpraveen/novart.git
      branch: main
    source_dir: .
    run_command: python manage.py migrate --noinput
    envs:
      - key: DJANGO_SECRET_KEY
        type: SECRET
        value: EV[1:lgeIZg+A2H+qUG8+O79Oq4+5BLhaZDEm:ENgcR4e9jP5j8V08VLhOvK2m8epVcqfHzA==]
        scope: RUN_AND_BUILD_TIME
      - key: DJANGO_ALLOWED_HOSTS
        value: ${APP_DOMAIN}
        scope: RUN_AND_BUILD_TIME
      - key: DJANGO_DEBUG
        value: "0"
        scope: RUN_AND_BUILD_TIME
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://${APP_DOMAIN}
        scope: RUN_AND_BUILD_TIME
      - key: DATABASE_URL
        type: SECRET
        value: EV[1:LQ4no82jp8/fafbhZzbJa8GYYK3veJWA:8spjjByNzhMF6pTokg55CTKLmkLVI+aP8eslpqMaYYXHMNqSAFSjd0OrBibOiX/oQQA5l27k9dw0Cc+Qz4X3tUwUDugJMHbTY7BQaxpwiR7/lRtlGPe+9QI5qUJN5mzBxGWQrb4DNZg/jQYNpJk4W1dEYzvB1gmcYxh1HwvS1QW4Uf+209ebPXPbsnvu0/XaR+QxJMuW]
        scope: RUN_AND_BUILD_TIME
